_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 29
DATASETS:
  TRAIN: ("sidewalk_bbox_train",)
  TEST: ("sidewalk_bbox_val",)
#  TEST: ("sidewalk_polygon_test",)
